service: dynamodb-stream-to-elasticsearch

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  create-job:
    handler: handler.createJob
    events:
      - httpApi:
          cors: true
          method: post
          path: /create-job

resources:
  - ${file(./dynamodb.yml)}
  - ${file(./elasticsearch.yml)}

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-dotenv-plugin
  - serverless-offline


