service: dynamodb-stream-to-elasticsearch

frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          cors: true
          method: get
          path: /hello

plugins:
  - serverless-offline


